# Generated by Django 5.1.1 on 2024-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reason',
            field=models.CharField(default='auction_payment', max_length=10),
        ),
    ]
