# Generated by Django 5.1.1 on 2024-09-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionManager', '0002_auction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
