# Generated by Django 5.1.1 on 2024-09-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuctionManager', '0003_alter_auction_current_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='starting_price',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
